type: MyScale
args:
  msc_host: "msc-1decbcc9.us-east-1.aws.staging.myscale.cloud"
  msc_port: 443
  msc_user: chatdata
  msc_pass: myscale_rocks
  table_name: wiki.Wikipedia
  num_filtered: 100
  two_staged: true
  kw_topk: 10