evaluator: 
  type: mcsa
  outfile: default-output.json
  dataset: 
    type: "mmlu"
  model:
    type: "chatgpt35"
    args:
      name: "gpt-3.5-turbo"
      api_key: "sk-some-super-secret-key-you-will-never-know"
      system_prompt: ""
    run_args:
      temperature: 0.0
      top_p: 1.0
      max_tokens: 30
      stop: "\n\n"
  transform:
    nodes:
      - type: MyScale
        args:
          msc_host: "msc-1decbcc9.us-east-1.aws.staging.myscale.cloud"
          msc_port: 443
          msc_user: chatdata
          msc_pass: myscale_rocks
          table_name: wiki.Wikipedia
  